{{- if .Values.ingress.enabled -}}
{{- $fullName := include "webapi.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- toYaml .Values.ingress.hosts | nindent 2 }}  
  gateways:
  - {{ .Values.ingress.gateway }}
  http:  
  - match:
    - uri:
        prefix: "{{ .Values.ingress.path }}"
    rewrite:
      uri: "/"
    route:
    - destination: 
        host: "{{ $fullName }}.{{ .Values.namespace }}.svc.cluster.local" 
        port:
          number: {{ $svcPort }}
{{- end }}