{{- if .Values.ingress.enabled -}}
{{- $fullName := include "webapi.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.ingress.hosts }}
  hosts:
  {{- toYaml . | nindent 2 }}  
  {{- end }}
  {{- with .Values.ingress.gateway }}
  gateways:
  {{- toYaml . | nindent 2 }}  
  {{- end }}
  http:  
  - match:
    - uri:
        prefix: "{{ .Values.ingress.path }}"
    rewrite:
      uri: "/"
    route:
    - destination: 
        host: "{{ $fullName }}.{{ .Values.namespace }}.svc.cluster.local" 
        port:
          number: {{ $svcPort }}
{{- end }}