apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "webapi.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "webapi.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: {{ include "webapi.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}