apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "webapi.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']